### ISSUE TITLE
Summing up translations in animation

### ISSUE THREAD

**Issue by jacek-bulatek** [jacek-bulatek/java-app#3]
That could be a major problem - using "x" "y" animations could not be the solution if original parameters dont change after animation. We can do that manually, or using fillIn method I saw it once somewhere (this method set new view properties after animation ends, but I'm not sure if it is the case in used Animator).

**Comment by jacek-bulatek** [comment]
https://developer.android.com/guide/topics/graphics/prop-animation.html

**Comment by mbulatek** [comment]
Fixed by 7c011cd3a377396b0ceca63701d57149500e8e53
